/* Generated By:JavaCC: Do not edit this line. PS4TokenizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PS4TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAB = 1;
  /** RegularExpression Id. */
  int CR = 2;
  /** RegularExpression Id. */
  int OPERATOR = 3;
  /** RegularExpression Id. */
  int PUNCTUATION = 4;
  /** RegularExpression Id. */
  int SPECIAL_ENTITY = 5;
  /** RegularExpression Id. */
  int EMAIL = 6;
  /** RegularExpression Id. */
  int DOMAIN = 7;
  /** RegularExpression Id. */
  int PHONE_NUMBER = 8;
  /** RegularExpression Id. */
  int EQUATION = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int WORD2 = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int SPACE = 13;
  /** RegularExpression Id. */
  int NEWLINE = 14;
  /** RegularExpression Id. */
  int MISC = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TAB>",
    "<CR>",
    "<OPERATOR>",
    "<PUNCTUATION>",
    "<SPECIAL_ENTITY>",
    "<EMAIL>",
    "<DOMAIN>",
    "<PHONE_NUMBER>",
    "<EQUATION>",
    "<NUMBER>",
    "<WORD2>",
    "<WORD>",
    "<SPACE>",
    "<NEWLINE>",
    "<MISC>",
  };

}
